void ppd_console_entrypoint_setearPosicionCabezal(uint32 pista, uint32 sector);
float ppd_console_entrypoint_TiempoConsumido(uint32 pistaSolicitada, uint32 sectorSolicitado);
PistaSector ppd_console_entrypoint_getPosicionCabezal();
